### ISSUE TITLE
A new build does not remove all old versions of the draft

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/bfd-secure-sequence-numbers#22]
Once the draft version gets updated (via git tags), a new build is supposed to remove the older versions of the model. Currently, it does not.

**Comment by jhaas-pfrc** [comment]
If by "older versions", you mean -nn.txt generated entries, removing them is probably not what we want.  Among other things it can make grabbing a version for rfcdiff challenging.

**Comment by mjethanandani** [comment]
Older version of the draft, like the one you cite, are always available from the datatracker, for tools such as iddiff tool.

**Comment by jhaas-pfrc** [comment]
... which if I place in the directory via curl -O to run locally, the build system shouldn't molest.

Note that this is different than "the -nn.txt shouldn't be locally checked in".  I'm of mixed opinion on that, but think it's a reasonable choice on a per-repository basis.
